name: Windows cx_Freeze Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cx_Freeze
          if (Test-Path 'requirements.txt') {
            python -m pip install -r 'requirements.txt'
          }
      - name: Build with cx_Freeze
        run: |
          python -m cx_Freeze yapbuddy.py --include-files assets

      - name: Package build
        run: |
          set BUILD_DIR=build\exe.win-amd64-3.13
          powershell Compress-Archive -Path %BUILD_DIR%\* -DestinationPath build\yapbuddy-portable.zip
          tar -czf build/yapbuddy-portable.tar.gz -C %BUILD_DIR% .
          

      - name: Upload portable archives
        uses: actions/upload-artifact@v4
        with:
          name: yapbuddy-portable
          path: |
            build/yapbuddy-portable.zip
            build/yapbuddy-portable.tar.gz
